// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuxRrWP07NV_chaghu55i15qawwArLt6s',
    appId: '1:705926124857:android:33a06fe0f4583ef01104e8',
    messagingSenderId: '705926124857',
    projectId: 'quizapp-c38fc',
    storageBucket: 'quizapp-c38fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalaLVpYOhCpmOBLvQcUjPFp3tCSYBFq8',
    appId: '1:705926124857:ios:8f6319739187103b1104e8',
    messagingSenderId: '705926124857',
    projectId: 'quizapp-c38fc',
    storageBucket: 'quizapp-c38fc.appspot.com',
    androidClientId: '705926124857-45chedt8fkgg60f224iklti5m6glmoiu.apps.googleusercontent.com',
    iosClientId: '705926124857-h7f1a3p3fb345vrnnff9kijvcvuvrkvt.apps.googleusercontent.com',
    iosBundleId: 'com.snakeoilsoftware.quizapp',
  );
}
